[project]
name = "climpt"
version = "0.1.0"
description = "Climpt - Clipboard Prompt Manager: Легковесное приложение для хранения и вставки текстовых промптов"
authors = ["Ostarkov S.N. ostarkovstepan@gmail.com"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
start = "python main.py"
build = "pyinstaller --onefile --windowed main.py"

[dependencies]
python = ">=3.10"
wxpython = "*"
pyperclip = "*"
pyinstaller = "*"

[pypi-dependencies]
keyboard = "*"