[tool.pixi.project]
name = "climpt"
version = "0.1.0"
description = "Climpt - Clipboard Prompt Manager: Легковесное приложение для хранения и вставки текстовых промптов"
authors = ["Ostarkov S.N. ostarkovstepan@gmail.com"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pixi.tasks]
start = "python main.py"
build = "pyinstaller --onefile --windowed main.py"
debug = "python main.py -vv"

[tool.pixi.dependencies]
python = ">=3.10"
pyperclip = "*"
pyinstaller = "*"
click = ">=8.2.1,<9"

[tool.pixi.pypi-dependencies]
keyboard = "*"
pyqt6 = "*"

[tool.pixi.environments]
dev = ["jupyter"]

[tool.pixi.feature.jupyter.dependencies]
ipykernel = "*"
pip = "*"
